language: minimal
sudo: required
services:
  - docker
  
before_install:
  - docker build -t omawnakw/docker-lab-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true omawnakw/docker-lab-ci npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-central-1" 
  app: "docker-lab-ci"
  env: "DockerLabCi-env"
  bucket_name: "elasticbeanstalk-eu-central-1-567500519036"
  bucket_path: "docker-lab-ci"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
